/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import PromoOpen from "./TJ/Promo/script/PromoOpen"
import ButtonScale from "./TJ/Promo/script/ButtonScale"
import PromoItem from "./TJ/Promo/script/PromoItem"
import P201 from "./TJ/Promo/script/P201"
import P202 from "./TJ/Promo/script/P202"
import P204 from "./TJ/Promo/script/P204"
import P205 from "./TJ/Promo/script/P205"
import P106 from "./TJ/Promo/script/P106"
import UIAdvertising from "./script/Game/UIAdvertising"
import UIAnchorXD from "./script/Game/UIAnchorXD"
import UICaidanPifu from "./script/Game/UICaidanPifu"
import SkinItem from "./ZhuanPan/SkinItem"
import CaiDanQiang from "./ZhuanPan/CaiDanQiang"
import UICheckIn from "./script/Game/UICheckIn"
import UIDefeated from "./script/Game/UIDefeated"
import UIExecutionHint from "./script/Game/UIExecutionHint"
import UILoding from "./script/Game/UILoding"
import UIMain from "./script/Game/UIMain"
import UIMain_Aisle from "./script/Game/UIMain_Aisle"
import UIMain_Dog from "./script/Game/UIMain_Dog"
import UIMain_Rival from "./script/Game/UIMain_Rival"
import UIMain_Bonfire from "./script/Game/UIMain_Bonfire"
import UIMain_Gongzhu from "./script/Game/UIMain_Gongzhu"
import UIMain_Wangzi from "./script/Game/UIMain_Wangzi"
import UIMain_Houzi from "./script/Game/UIMain_Houzi"
import UIMain_StaticDog from "./script/Game/UIMain_StaticDog"
import UIMain_Houma from "./script/Game/UIMain_Houma"
import UIMain_Room from "./script/Game/UIMain_Room"
import UIPassHint from "./script/Game/UIPassHint"
import UIPuase from "./script/Game/UIPuase"
import UIPifu from "./script/Game/UIPifu"
import UIPifuTry from "./script/Game/UIPifuTry"
import UIRedeem from "./script/Game/UIRedeem"
import UISet from "./script/Game/UISet"
import UIShare from "./script/Game/UIShare"
import UISmallHint from "./script/Game/UISmallHint"
import UIStart from "./script/Game/UIStart"
import UIStart_House from "./script/Game/UIStart_House"
import RotateSelfPro from "./ZhuanPan/RotateSelfPro"
import ZhuanPan from "./ZhuanPan/ZhuanPan"
import UIVictory from "./script/Game/UIVictory"
import UIVictoryBox_Cell from "./script/Game/UIVictoryBox_Cell"
import UIVictoryBox from "./script/Game/UIVictoryBox"
import UIXDpifu from "./script/Game/UIXDpifu"
import UILoding_ExecutionNumNode from "./script/Game/UILoding_ExecutionNumNode"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("TJ/Promo/script/PromoOpen.ts",PromoOpen);
        reg("TJ/Promo/script/ButtonScale.ts",ButtonScale);
        reg("TJ/Promo/script/PromoItem.ts",PromoItem);
        reg("TJ/Promo/script/P201.ts",P201);
        reg("TJ/Promo/script/P202.ts",P202);
        reg("TJ/Promo/script/P204.ts",P204);
        reg("TJ/Promo/script/P205.ts",P205);
        reg("TJ/Promo/script/P106.ts",P106);
        reg("script/Game/UIAdvertising.ts",UIAdvertising);
        reg("script/Game/UIAnchorXD.ts",UIAnchorXD);
        reg("script/Game/UICaidanPifu.ts",UICaidanPifu);
        reg("ZhuanPan/SkinItem.ts",SkinItem);
        reg("ZhuanPan/CaiDanQiang.ts",CaiDanQiang);
        reg("script/Game/UICheckIn.ts",UICheckIn);
        reg("script/Game/UIDefeated.ts",UIDefeated);
        reg("script/Game/UIExecutionHint.ts",UIExecutionHint);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/Game/UIMain.ts",UIMain);
        reg("script/Game/UIMain_Aisle.ts",UIMain_Aisle);
        reg("script/Game/UIMain_Dog.ts",UIMain_Dog);
        reg("script/Game/UIMain_Rival.ts",UIMain_Rival);
        reg("script/Game/UIMain_Bonfire.ts",UIMain_Bonfire);
        reg("script/Game/UIMain_Gongzhu.ts",UIMain_Gongzhu);
        reg("script/Game/UIMain_Wangzi.ts",UIMain_Wangzi);
        reg("script/Game/UIMain_Houzi.ts",UIMain_Houzi);
        reg("script/Game/UIMain_StaticDog.ts",UIMain_StaticDog);
        reg("script/Game/UIMain_Houma.ts",UIMain_Houma);
        reg("script/Game/UIMain_Room.ts",UIMain_Room);
        reg("script/Game/UIPassHint.ts",UIPassHint);
        reg("script/Game/UIPuase.ts",UIPuase);
        reg("script/Game/UIPifu.ts",UIPifu);
        reg("script/Game/UIPifuTry.ts",UIPifuTry);
        reg("script/Game/UIRedeem.ts",UIRedeem);
        reg("script/Game/UISet.ts",UISet);
        reg("script/Game/UIShare.ts",UIShare);
        reg("script/Game/UISmallHint.ts",UISmallHint);
        reg("script/Game/UIStart.ts",UIStart);
        reg("script/Game/UIStart_House.ts",UIStart_House);
        reg("ZhuanPan/RotateSelfPro.ts",RotateSelfPro);
        reg("ZhuanPan/ZhuanPan.ts",ZhuanPan);
        reg("script/Game/UIVictory.ts",UIVictory);
        reg("script/Game/UIVictoryBox_Cell.ts",UIVictoryBox_Cell);
        reg("script/Game/UIVictoryBox.ts",UIVictoryBox);
        reg("script/Game/UIXDpifu.ts",UIXDpifu);
        reg("script/Game/UILoding_ExecutionNumNode.ts",UILoding_ExecutionNumNode);
    }
}
GameConfig.init();